### PR TITLE
Fix for issue 6 - adding contribution templates and updating the README

### LINKED ISSUE #6: Add template for contributions
All documentation pages follow a fixed template. If we add the template to the repo and README, then it will be easy for anyone to make a contribution.

### PR DESCRIPTION
**Pull request by hillalex**
Fixes https://github.com/HealthEconomicsHackathon/SHEPRD/issues/6

Contains commits from https://github.com/HealthEconomicsHackathon/SHEPRD/pull/15 so shouldn't be reviewed until that one has been merged.

* adds templates under a `templates` folder
* updates README
* tidies up existing content to conform to the template better

Please have a read of these updated instructions and see if they are clear to you: https://github.com/HealthEconomicsHackathon/SHEPRD/blob/d101a58e70c6cafd77cbc1c480ad8e62b99bd463/README.md

I think it'd be great to have some guidelines about the content of a contribution as well. I'm imagining contributions would fall into the following categories:

1. a correction to some existing package or model description
1. a new type of model that isn't already documented or a sub-type of an existing section
1. a new package that isn't already mentioned
1. full details of any of the packages mentioned in the "Other packages to explore but not detailed here" sections

Does this sound right to you?

### CODE REVIEW

**Comment by NikkiR08** [comment]
Great. I will approve. Yes agree to all the suggested types on changes (e.g. 1 - 4).
Only thing I still find slightly confusing is perhaps is the numbering of issues and the text - so i could put here #17 in answering #16 (or is is only for committed issues in the issue file and not any further correspondence)?

**Comment by hillalex** [comment]
> Great. I will approve. Yes agree to all the suggested types on changes (e.g. 1 - 4).
> Only thing I still find slightly confusing is perhaps is the numbering of issues and the text - so i could put here #17 in answering #16 (or is is only for committed issues in the issue file and not any further correspondence)?

Sorry I'm struggling to understand this question! If you write "fixes #6" in a pull request description then when the pull request is merged issue number 6 (from these issues: https://github.com/HealthEconomicsHackathon/SHEPRD/issues)  gets automatically marked as resolved. And in general whenever you write #N then Github will auto-complete a link to Github issue number N. Does that make things any clearer?

**Comment by hillalex** [comment]
As an example you can see that [this issue](https://github.com/HealthEconomicsHackathon/SHEPRD/issues/13) is now closed because you merged a pull request that referenced it - hope that helps!

**Review by NikkiR08 — APPROVED** [review]

**Comment by NikkiR08** [comment]
Ok got it, sorry i think i confused myself! And I can see the subheadings are now working on the webpage, great!!

**Pull request merged**
